export const dummyCourses = [
  {
    id: 1,
    title: 'Complete Web Development Bootcamp 2024',
    description:
      'Master web development from scratch. Learn HTML, CSS, JavaScript, React, Node.js, and MongoDB to build modern, responsive websites and applications.',
    thumbnail:
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    price: '$89.99',
    discount_price: '$129.99',
    discount_percentage: 30,
    days_left: 3,
    course_type: 'paid',
    language: 'English',
    level: 'Beginner',
    subject: 'Web Development',
    total_enrollments: 12543,
    total_videos: 245,
    requirements: 'Basic computer knowledge and internet connection',
    teacher: {
      id: 1,
      first_name: 'Sarah',
      last_name: 'Johnson',
      username: 'sarahj_dev',
      email: 'sarah.johnson@example.com',
      bio: 'Full-stack developer with 10 years of experience',
      profile_picture: 'https://i.pravatar.cc/150?img=1',
      average_rating: 4.8,
      total_students: 45000,
      total_courses: 12,
      courses_created: [
        {
          id: 2,
          title: 'Advanced JavaScript Patterns',
          thumbnail:
            'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800',
          subject: 'JavaScript',
          rating: 4.7,
          total_reviews: 890,
          total_enrollments: 5600,
          duration: '8h 30m',
          total_lessons: 65,
          level: 'Advanced',
          price: '$79.99',
          discount_price: '$99.99',
        },
        {
          id: 3,
          title: 'React Masterclass 2024',
          thumbnail:
            'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
          subject: 'React',
          rating: 4.9,
          total_reviews: 1200,
          total_enrollments: 8900,
          duration: '12h 15m',
          total_lessons: 98,
          level: 'Intermediate',
          price: '$94.99',
          discount_price: '$119.99',
        },
      ],
      feedbacks: [
        {
          id: 1,
          rating: 5,
          feedback_text:
            'Absolutely incredible course! Sarah explains complex concepts in such a simple way. The hands-on projects really helped solidify my understanding.',
          created_at: '2024-10-15T10:30:00Z',
          user: {
            first_name: 'Michael',
            last_name: 'Chen',
            username: 'mchen92',
          },
        },
        {
          id: 2,
          rating: 5,
          feedback_text:
            "Best investment I've made in my career. Landed a job as a junior developer within 2 months of completing this course!",
          created_at: '2024-10-20T14:45:00Z',
          user: {
            first_name: 'Emma',
            last_name: 'Davis',
            username: 'emma_codes',
          },
        },
        {
          id: 3,
          rating: 4,
          feedback_text:
            'Great content and well-structured. Only minor issue was some videos could be updated to reflect the latest frameworks.',
          created_at: '2024-10-22T09:15:00Z',
          user: {
            first_name: 'James',
            last_name: 'Wilson',
            username: 'jwilson_dev',
          },
        },
      ],
    },
    topics: [
      {
        id: 1,
        title: 'Introduction to Web Development',
        video_count: 8,
        quiz_count: 2,
        assignment_count: 1,
        videos: [
          {
            id: 1,
            title: 'What is Web Development?',
            duration: '00:15:30',
          },
          {
            id: 2,
            title: 'Setting Up Your Development Environment',
            duration: '00:22:45',
          },
          {
            id: 3,
            title: 'Understanding Client-Server Architecture',
            duration: '00:18:20',
          },
          {
            id: 4,
            title: 'Version Control with Git',
            duration: '00:25:15',
          },
          {
            id: 5,
            title: 'Introduction to HTML',
            duration: '00:20:30',
          },
          {
            id: 6,
            title: 'HTML Elements and Structure',
            duration: '00:28:10',
          },
          {
            id: 7,
            title: 'Forms and Input Elements',
            duration: '00:24:45',
          },
          {
            id: 8,
            title: 'Semantic HTML Best Practices',
            duration: '00:19:50',
          },
        ],
      },
      {
        id: 2,
        title: 'CSS Fundamentals',
        video_count: 12,
        quiz_count: 3,
        assignment_count: 2,
        videos: [
          {
            id: 9,
            title: 'Introduction to CSS',
            duration: '00:16:40',
          },
          {
            id: 10,
            title: 'Selectors and Specificity',
            duration: '00:21:15',
          },
          {
            id: 11,
            title: 'Box Model Explained',
            duration: '00:23:30',
          },
          {
            id: 12,
            title: 'Flexbox Layout',
            duration: '00:32:20',
          },
          {
            id: 13,
            title: 'CSS Grid System',
            duration: '00:35:45',
          },
          {
            id: 14,
            title: 'Responsive Design Principles',
            duration: '00:28:50',
          },
          {
            id: 15,
            title: 'Media Queries',
            duration: '00:19:30',
          },
          {
            id: 16,
            title: 'CSS Animations and Transitions',
            duration: '00:26:15',
          },
          {
            id: 17,
            title: 'CSS Variables',
            duration: '00:18:45',
          },
          {
            id: 18,
            title: 'Preprocessors: SASS/SCSS',
            duration: '00:30:20',
          },
          {
            id: 19,
            title: 'Modern CSS Features',
            duration: '00:22:35',
          },
          {
            id: 20,
            title: 'CSS Best Practices',
            duration: '00:20:10',
          },
        ],
      },
      {
        id: 3,
        title: 'JavaScript Essentials',
        video_count: 15,
        quiz_count: 4,
        assignment_count: 3,
        videos: [
          {
            id: 21,
            title: 'JavaScript Basics',
            duration: '00:25:30',
          },
          {
            id: 22,
            title: 'Variables and Data Types',
            duration: '00:22:45',
          },
          {
            id: 23,
            title: 'Functions and Scope',
            duration: '00:28:20',
          },
          {
            id: 24,
            title: 'Arrays and Objects',
            duration: '00:30:15',
          },
          {
            id: 25,
            title: 'DOM Manipulation',
            duration: '00:35:40',
          },
          {
            id: 26,
            title: 'Event Handling',
            duration: '00:27:50',
          },
          {
            id: 27,
            title: 'Asynchronous JavaScript',
            duration: '00:32:25',
          },
          {
            id: 28,
            title: 'Promises and Async/Await',
            duration: '00:29:35',
          },
          {
            id: 29,
            title: 'Fetch API and AJAX',
            duration: '00:26:15',
          },
          {
            id: 30,
            title: 'ES6+ Features',
            duration: '00:31:45',
          },
          {
            id: 31,
            title: 'Error Handling',
            duration: '00:20:30',
          },
          {
            id: 32,
            title: 'Local Storage and Session Storage',
            duration: '00:23:20',
          },
          {
            id: 33,
            title: 'JavaScript Modules',
            duration: '00:25:50',
          },
          {
            id: 34,
            title: 'Object-Oriented JavaScript',
            duration: '00:33:15',
          },
          {
            id: 35,
            title: 'JavaScript Testing Basics',
            duration: '00:28:40',
          },
        ],
      },
      {
        id: 4,
        title: 'React Framework',
        video_count: 18,
        quiz_count: 5,
        assignment_count: 4,
        videos: [
          {
            id: 36,
            title: 'Introduction to React',
            duration: '00:24:30',
          },
          {
            id: 37,
            title: 'JSX Syntax',
            duration: '00:20:45',
          },
          {
            id: 38,
            title: 'Components and Props',
            duration: '00:28:20',
          },
          {
            id: 39,
            title: 'State Management',
            duration: '00:32:15',
          },
          {
            id: 40,
            title: 'React Hooks - useState',
            duration: '00:26:40',
          },
          {
            id: 41,
            title: 'React Hooks - useEffect',
            duration: '00:30:25',
          },
          {
            id: 42,
            title: 'React Router',
            duration: '00:35:50',
          },
          {
            id: 43,
            title: 'Context API',
            duration: '00:29:35',
          },
          {
            id: 44,
            title: 'Form Handling in React',
            duration: '00:27:15',
          },
          {
            id: 45,
            title: 'API Integration',
            duration: '00:33:45',
          },
          {
            id: 46,
            title: 'Custom Hooks',
            duration: '00:25:30',
          },
          {
            id: 47,
            title: 'Performance Optimization',
            duration: '00:31:20',
          },
          {
            id: 48,
            title: 'React Testing Library',
            duration: '00:28:50',
          },
          {
            id: 49,
            title: 'Redux Fundamentals',
            duration: '00:36:15',
          },
          {
            id: 50,
            title: 'Redux Toolkit',
            duration: '00:34:40',
          },
          {
            id: 51,
            title: 'Building a Complete App - Part 1',
            duration: '00:42:25',
          },
          {
            id: 52,
            title: 'Building a Complete App - Part 2',
            duration: '00:45:30',
          },
          {
            id: 53,
            title: 'Deployment Strategies',
            duration: '00:30:15',
          },
        ],
      },
    ],
    videos: [
      {
        id: 1,
        title: 'What is Web Development?',
        duration: '00:15:30',
      },
      {
        id: 2,
        title: 'Setting Up Your Development Environment',
        duration: '00:22:45',
      },
    ],
    assignments: [
      {
        id: 1,
        title: 'Build Your First Website',
      },
      {
        id: 2,
        title: 'Create a Responsive Portfolio',
      },
      {
        id: 3,
        title: 'JavaScript Mini Project',
      },
      {
        id: 4,
        title: 'React Todo Application',
      },
    ],
  },
  {
    id: 2,
    title: 'Python for Data Science and Machine Learning',
    description:
      'Learn Python programming from basics to advanced. Master data analysis, visualization, machine learning algorithms, and build real-world AI projects.',
    thumbnail:
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    price: '$79.99',
    discount_price: '$109.99',
    discount_percentage: 27,
    days_left: 5,
    course_type: 'paid',
    language: 'English',
    level: 'Intermediate',
    subject: 'Data Science',
    total_enrollments: 9876,
    total_videos: 189,
    requirements: 'Basic programming knowledge recommended',
    teacher: {
      id: 2,
      first_name: 'David',
      last_name: 'Martinez',
      username: 'david_ml',
      email: 'david.martinez@example.com',
      bio: 'Data Scientist and ML Engineer at Tech Corp',
      profile_picture: 'https://i.pravatar.cc/150?img=12',
      average_rating: 4.9,
      total_students: 32000,
      total_courses: 8,
      courses_created: [],
      feedbacks: [
        {
          id: 4,
          rating: 5,
          feedback_text:
            "David's teaching style is exceptional. Complex ML concepts become easy to understand!",
          created_at: '2024-10-18T11:20:00Z',
          user: {
            first_name: 'Lisa',
            last_name: 'Anderson',
            username: 'lisa_data',
          },
        },
        {
          id: 5,
          rating: 5,
          feedback_text:
            'The hands-on projects are amazing. I built my first ML model in week 2!',
          created_at: '2024-10-25T16:30:00Z',
          user: {
            first_name: 'Robert',
            last_name: 'Taylor',
            username: 'rob_analytics',
          },
        },
      ],
    },
    topics: [
      {
        id: 5,
        title: 'Python Fundamentals',
        video_count: 10,
        quiz_count: 3,
        assignment_count: 2,
        videos: [
          {
            id: 54,
            title: 'Python Installation and Setup',
            duration: '00:18:30',
          },
          {
            id: 55,
            title: 'Variables and Data Types',
            duration: '00:22:15',
          },
        ],
      },
    ],
    videos: [],
    assignments: [],
  },
  {
    id: 3,
    title: 'Digital Marketing Masterclass 2024',
    description:
      'Complete digital marketing course covering SEO, social media marketing, email marketing, Google Ads, Facebook Ads, and content marketing strategies.',
    thumbnail:
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    price: '$69.99',
    discount_price: '$99.99',
    discount_percentage: 30,
    days_left: 2,
    course_type: 'paid',
    language: 'English',
    level: 'Beginner',
    subject: 'Marketing',
    total_enrollments: 15234,
    total_videos: 156,
    requirements: 'No prior experience required',
    teacher: {
      id: 3,
      first_name: 'Jennifer',
      last_name: 'Lee',
      username: 'jen_marketing',
      email: 'jennifer.lee@example.com',
      bio: 'Digital Marketing Expert with 15+ years experience',
      profile_picture: 'https://i.pravatar.cc/150?img=5',
      average_rating: 4.7,
      total_students: 50000,
      total_courses: 15,
      courses_created: [],
      feedbacks: [
        {
          id: 6,
          rating: 5,
          feedback_text:
            "Jennifer's course helped me grow my business by 300%! Highly recommended.",
          created_at: '2024-10-12T09:45:00Z',
          user: {
            first_name: 'Mark',
            last_name: 'Brown',
            username: 'mark_entrepreneur',
          },
        },
      ],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 4,
    title: 'UI/UX Design Fundamentals',
    description:
      'Learn user interface and user experience design from scratch. Master Figma, design principles, user research, wireframing, and prototyping.',
    thumbnail:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    price: 'Free',
    discount_price: null,
    discount_percentage: null,
    days_left: null,
    course_type: 'free',
    language: 'English',
    level: 'Beginner',
    subject: 'Design',
    total_enrollments: 23456,
    total_videos: 87,
    requirements: 'Creative mindset and passion for design',
    teacher: {
      id: 4,
      first_name: 'Alex',
      last_name: 'Thompson',
      username: 'alex_design',
      email: 'alex.thompson@example.com',
      bio: 'Senior UX Designer at Apple',
      profile_picture: 'https://i.pravatar.cc/150?img=33',
      average_rating: 4.9,
      total_students: 67000,
      total_courses: 10,
      courses_created: [],
      feedbacks: [
        {
          id: 7,
          rating: 5,
          feedback_text:
            "Alex's design principles are industry-leading. This course changed my career!",
          created_at: '2024-10-20T14:20:00Z',
          user: {
            first_name: 'Sophie',
            last_name: 'Williams',
            username: 'sophie_designer',
          },
        },
      ],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 5,
    title: 'Mobile App Development with Flutter',
    description:
      'Build beautiful, natively compiled applications for mobile, web, and desktop from a single codebase using Flutter and Dart programming language.',
    thumbnail:
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
    price: '$84.99',
    discount_price: '$119.99',
    discount_percentage: 29,
    days_left: 4,
    course_type: 'paid',
    language: 'English',
    level: 'Intermediate',
    subject: 'Mobile Development',
    total_enrollments: 8765,
    total_videos: 198,
    requirements: 'Basic programming knowledge required',
    teacher: {
      id: 5,
      first_name: 'Chris',
      last_name: 'Anderson',
      username: 'chris_flutter',
      email: 'chris.anderson@example.com',
      bio: 'Flutter GDE and Mobile Development Expert',
      profile_picture: 'https://i.pravatar.cc/150?img=14',
      average_rating: 4.8,
      total_students: 28000,
      total_courses: 7,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 6,
    title: 'Cybersecurity Essentials',
    description:
      'Comprehensive cybersecurity course covering network security, ethical hacking, penetration testing, cryptography, and security best practices.',
    thumbnail:
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
    price: '$94.99',
    discount_price: '$129.99',
    discount_percentage: 27,
    days_left: 6,
    course_type: 'paid',
    language: 'English',
    level: 'Advanced',
    subject: 'Cybersecurity',
    total_enrollments: 6543,
    total_videos: 167,
    requirements: 'Networking fundamentals required',
    teacher: {
      id: 6,
      first_name: 'Rachel',
      last_name: 'Kim',
      username: 'rachel_security',
      email: 'rachel.kim@example.com',
      bio: 'Certified Ethical Hacker and Security Consultant',
      profile_picture: 'https://i.pravatar.cc/150?img=9',
      average_rating: 4.9,
      total_students: 19000,
      total_courses: 5,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 7,
    title: 'Photography Masterclass: From Beginner to Pro',
    description:
      'Learn professional photography techniques, composition, lighting, post-processing with Lightroom and Photoshop, and build your photography portfolio.',
    thumbnail:
      'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
    price: '$59.99',
    discount_price: '$89.99',
    discount_percentage: 33,
    days_left: 7,
    course_type: 'paid',
    language: 'English',
    level: 'Beginner',
    subject: 'Photography',
    total_enrollments: 11234,
    total_videos: 134,
    requirements: 'Any camera (DSLR, mirrorless, or smartphone)',
    teacher: {
      id: 7,
      first_name: 'Thomas',
      last_name: 'Wright',
      username: 'tom_photographer',
      email: 'thomas.wright@example.com',
      bio: 'Award-winning photographer with 20 years experience',
      profile_picture: 'https://i.pravatar.cc/150?img=15',
      average_rating: 4.8,
      total_students: 34000,
      total_courses: 9,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 8,
    title: 'Cloud Computing with AWS',
    description:
      'Master Amazon Web Services (AWS) cloud platform. Learn EC2, S3, Lambda, RDS, CloudFormation, and prepare for AWS Solutions Architect certification.',
    thumbnail:
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    price: '$89.99',
    discount_price: '$119.99',
    discount_percentage: 25,
    days_left: 3,
    course_type: 'paid',
    language: 'English',
    level: 'Intermediate',
    subject: 'Cloud Computing',
    total_enrollments: 7891,
    total_videos: 213,
    requirements: 'Basic IT knowledge and Linux fundamentals',
    teacher: {
      id: 8,
      first_name: 'Maria',
      last_name: 'Garcia',
      username: 'maria_cloud',
      email: 'maria.garcia@example.com',
      bio: 'AWS Certified Solutions Architect Professional',
      profile_picture: 'https://i.pravatar.cc/150?img=20',
      average_rating: 4.9,
      total_students: 25000,
      total_courses: 6,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 9,
    title: 'Blockchain and Cryptocurrency Development',
    description:
      'Learn blockchain technology, smart contracts, Solidity programming, DeFi applications, NFTs, and build decentralized applications on Ethereum.',
    thumbnail:
      'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
    price: '$99.99',
    discount_price: '$139.99',
    discount_percentage: 29,
    days_left: 5,
    course_type: 'paid',
    language: 'English',
    level: 'Advanced',
    subject: 'Blockchain',
    total_enrollments: 5432,
    total_videos: 178,
    requirements: 'JavaScript and programming experience required',
    teacher: {
      id: 9,
      first_name: 'Kevin',
      last_name: 'Nguyen',
      username: 'kevin_blockchain',
      email: 'kevin.nguyen@example.com',
      bio: 'Blockchain Developer and Crypto Consultant',
      profile_picture: 'https://i.pravatar.cc/150?img=52',
      average_rating: 4.7,
      total_students: 15000,
      total_courses: 4,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 10,
    title: 'Video Editing with Adobe Premiere Pro',
    description:
      'Professional video editing course. Master Premiere Pro, color grading, audio mixing, motion graphics, visual effects, and create stunning videos.',
    thumbnail:
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800',
    price: 'Free',
    discount_price: null,
    discount_percentage: null,
    days_left: null,
    course_type: 'free',
    language: 'English',
    level: 'Beginner',
    subject: 'Video Production',
    total_enrollments: 18765,
    total_videos: 112,
    requirements: 'Computer with Adobe Premiere Pro installed',
    teacher: {
      id: 10,
      first_name: 'Amanda',
      last_name: 'Rodriguez',
      username: 'amanda_video',
      email: 'amanda.rodriguez@example.com',
      bio: 'Professional Video Editor and Content Creator',
      profile_picture: 'https://i.pravatar.cc/150?img=45',
      average_rating: 4.8,
      total_students: 42000,
      total_courses: 11,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 11,
    title: 'Business Analytics and Intelligence',
    description:
      'Learn business analytics, data visualization with Power BI and Tableau, SQL for data analysis, and make data-driven business decisions.',
    thumbnail:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    price: '$74.99',
    discount_price: '$99.99',
    discount_percentage: 25,
    days_left: 4,
    course_type: 'paid',
    language: 'English',
    level: 'Intermediate',
    subject: 'Business Analytics',
    total_enrollments: 9321,
    total_videos: 145,
    requirements: 'Basic Excel knowledge helpful',
    teacher: {
      id: 11,
      first_name: 'Daniel',
      last_name: 'Parker',
      username: 'dan_analytics',
      email: 'daniel.parker@example.com',
      bio: 'Business Intelligence Consultant and Data Analyst',
      profile_picture: 'https://i.pravatar.cc/150?img=68',
      average_rating: 4.7,
      total_students: 31000,
      total_courses: 8,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
  {
    id: 12,
    title: 'Game Development with Unity',
    description:
      'Create 2D and 3D games using Unity game engine. Learn C# programming, game physics, animation, AI, multiplayer networking, and publish your games.',
    thumbnail:
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
    price: '$79.99',
    discount_price: '$109.99',
    discount_percentage: 27,
    days_left: 6,
    course_type: 'paid',
    language: 'English',
    level: 'Beginner',
    subject: 'Game Development',
    total_enrollments: 10567,
    total_videos: 189,
    requirements: 'Passion for games and willingness to learn',
    teacher: {
      id: 12,
      first_name: 'Ryan',
      last_name: 'Mitchell',
      username: 'ryan_gamedev',
      email: 'ryan.mitchell@example.com',
      bio: 'Unity Certified Developer and Indie Game Creator',
      profile_picture: 'https://i.pravatar.cc/150?img=70',
      average_rating: 4.8,
      total_students: 38000,
      total_courses: 12,
      courses_created: [],
      feedbacks: [],
    },
    topics: [],
    videos: [],
    assignments: [],
  },
];
