import TeacherImage from '@/assets/images/our-tutors/teacher.webp';

export const dummyData = [
  {
    id: 1,
    first_name: 'Ali',
    last_name: 'Raza',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Sc Physics' }],
    years_of_experience: '5 Years',
    expertise_areas: ['Physics', 'Mathematics'],
    age: 32,
    course_categories: ['A-Level'],
    preferred_teaching_methods: ['Online'],
  },
  {
    id: 2,
    first_name: 'Sara',
    last_name: 'Khan',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.A English' }],
    years_of_experience: '4 Years',
    expertise_areas: ['English Literature', 'IELTS'],
    age: 29,
    course_categories: ['Language'],
    preferred_teaching_methods: ['On-Campus'],
  },
  {
    id: 3,
    first_name: 'Hassan',
    last_name: 'Malik',
    profile_picture: TeacherImage,
    education: [{ degree: 'B.Sc Computer Science' }],
    years_of_experience: '3 Years',
    expertise_areas: ['Programming', 'Computer Basics'],
    age: 26,
    course_categories: ['IT'],
    preferred_teaching_methods: ['Online'],
  },
  {
    id: 4,
    first_name: 'Zainab',
    last_name: 'Naeem',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Phil Chemistry' }],
    years_of_experience: '6 Years',
    expertise_areas: ['Chemistry', 'Biology'],
    age: 33,
    course_categories: ['O-Level'],
    preferred_teaching_methods: ['Hybrid'],
  },
  {
    id: 5,
    first_name: 'Bilal',
    last_name: 'Ahmed',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Sc Mathematics' }],
    years_of_experience: '8 Years',
    expertise_areas: ['Mathematics'],
    age: 35,
    course_categories: ['A-Level'],
    preferred_teaching_methods: ['Online'],
  },
  {
    id: 6,
    first_name: 'Hina',
    last_name: 'Arif',
    profile_picture: TeacherImage,
    education: [{ degree: 'MBA Business Administration' }],
    years_of_experience: '4 Years',
    expertise_areas: ['Business Studies', 'Economics'],
    age: 30,
    course_categories: ['Commerce'],
    preferred_teaching_methods: ['On-Campus'],
  },
  {
    id: 7,
    first_name: 'Usman',
    last_name: 'Ali',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Sc Biology' }],
    years_of_experience: '5 Years',
    expertise_areas: ['Biology', 'Environmental Science'],
    age: 31,
    course_categories: ['O-Level'],
    preferred_teaching_methods: ['Online'],
  },
  {
    id: 8,
    first_name: 'Ayesha',
    last_name: 'Shahid',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.A Urdu' }],
    years_of_experience: '6 Years',
    expertise_areas: ['Urdu', 'Islamiat'],
    age: 34,
    course_categories: ['Language'],
    preferred_teaching_methods: ['On-Campus'],
  },
  {
    id: 9,
    first_name: 'Farhan',
    last_name: 'Iqbal',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Sc Geography' }],
    years_of_experience: '7 Years',
    expertise_areas: ['Geography', 'History'],
    age: 36,
    course_categories: ['Humanities'],
    preferred_teaching_methods: ['Hybrid'],
  },
  {
    id: 10,
    first_name: 'Nimra',
    last_name: 'Akram',
    profile_picture: TeacherImage,
    education: [{ degree: 'B.Ed Education' }],
    years_of_experience: '2 Years',
    expertise_areas: ['Primary Education'],
    age: 25,
    course_categories: ['Elementary'],
    preferred_teaching_methods: ['Online'],
  },
  {
    id: 11,
    first_name: 'Ahmad',
    last_name: 'Saleem',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Sc Economics' }],
    years_of_experience: '5 Years',
    expertise_areas: ['Economics', 'Business Math'],
    age: 32,
    course_categories: ['A-Level'],
    preferred_teaching_methods: ['On-Campus'],
  },
  {
    id: 12,
    first_name: 'Fatima',
    last_name: 'Zafar',
    profile_picture: TeacherImage,
    education: [{ degree: 'M.Phil Psychology' }],
    years_of_experience: '6 Years',
    expertise_areas: ['Psychology'],
    age: 33,
    course_categories: ['Social Sciences'],
    preferred_teaching_methods: ['Hybrid'],
  },
];
