export const dummyTutorRequests = [
  {
    id: 1,
    title: 'Tutor For Standard 9 Student - 3 Days / Week',
    description:
      'Looking for an experienced Chemistry and Physics tutor for Standard 9 student. The ideal candidate should have strong subject knowledge and ability to explain complex concepts in simple terms. Classes will be held 3 days per week.',
    student: {
      id: 1,
      username: 'student1',
      full_name: 'John Doe',
      profile_picture: '',
    },
    course: { id: 1, title: 'Standard 9', course_type: 'free' },
    subject_display: 'Chemistry, Physics',
    teaching_mode: 'in_person',
    budget_amount: '8000-9000',
    budget_type: 'per_month',
    duration_value: 3,
    duration_unit: 'month',
    location: 'Lahore',
    status: 'open',
    applications_count: 5,
    created_at: '2025-10-21',
    updated_at: '2025-10-23',
    time_ago: '4 Days Ago',
    deadline: '2025-11-15',
    can_apply: true,
    additional_notes:
      'Student is weak in practical concepts. Prefer tutor with hands-on teaching methodology.',
    selected_teacher: null,
  },
  {
    id: 2,
    title: 'Home Tutor Needed For O-Level Math & English',
    description:
      'Require a patient and experienced tutor with O-Level teaching background. Student needs help with Mathematics and English for upcoming exams. Must be able to provide practice materials and assignments.',
    student: {
      id: 2,
      username: 'student2',
      full_name: 'Sara Khan',
      profile_picture: '',
    },
    course: { id: 2, title: 'O-Level', course_type: 'paid' },
    subject_display: 'Mathematics, English',
    teaching_mode: 'in_person',
    budget_amount: '10000-12000',
    budget_type: 'per_month',
    duration_value: 4,
    duration_unit: 'month',
    location: 'Karachi',
    status: 'open',
    applications_count: 7,
    created_at: '2025-10-19',
    updated_at: '2025-10-22',
    time_ago: '6 Days Ago',
    deadline: '2025-11-10',
    can_apply: true,
    additional_notes:
      'Looking for a tutor who can help with exam preparation and confidence building.',
    selected_teacher: null,
  },
  {
    id: 3,
    title: 'Online Biology Tutor for A-Level Student',
    description:
      'Seeking an expert Biology tutor for A-Level preparation. Must have experience with Cambridge curriculum and be able to conduct engaging online sessions with proper study materials.',
    student: {
      id: 3,
      username: 'student3',
      full_name: 'Ahmed Ali',
      profile_picture: '',
    },
    course: { id: 3, title: 'A-Level', course_type: 'paid' },
    subject_display: 'Biology',
    teaching_mode: 'online',
    budget_amount: '15000',
    budget_type: 'per_month',
    duration_value: 6,
    duration_unit: 'month',
    location: 'Remote',
    status: 'open',
    applications_count: 12,
    created_at: '2025-10-18',
    updated_at: '2025-10-24',
    time_ago: '7 Days Ago',
    deadline: '2025-11-05',
    can_apply: true,
    additional_notes:
      'Must be available for weekend sessions. Previous A-Level teaching experience required.',
    selected_teacher: null,
  },
  {
    id: 4,
    title: 'Computer Science Tutor - Standard 10',
    description:
      'Need a tutor to teach Computer Science fundamentals including programming basics, algorithms, and theory. Student is interested in pursuing computer science in higher education.',
    student: {
      id: 4,
      username: 'student4',
      full_name: 'Fatima Hassan',
      profile_picture: '',
    },
    course: { id: 4, title: 'Standard 10', course_type: 'free' },
    subject_display: 'Computer Science',
    teaching_mode: 'in_person',
    budget_amount: '12000',
    budget_type: 'per_month',
    duration_value: 4,
    duration_unit: 'month',
    location: 'Islamabad',
    status: 'in_progress',
    applications_count: 15,
    created_at: '2025-10-15',
    updated_at: '2025-10-25',
    time_ago: '10 Days Ago',
    deadline: '2025-11-01',
    can_apply: false,
    additional_notes:
      'Hands-on coding practice required. Must bring own laptop for demonstrations.',
    selected_teacher: {
      id: 1,
      username: 'tech_tutor',
      full_name: 'Muhammad Usman',
      profile_picture: '',
    },
  },
  {
    id: 5,
    title: 'Urdu & Islamiyat Teacher for Standard 8',
    description:
      'Looking for a dedicated teacher to help with Urdu and Islamiyat subjects. Must have good command over both subjects and ability to teach religious concepts with proper understanding.',
    student: {
      id: 5,
      username: 'student5',
      full_name: 'Zainab Malik',
      profile_picture: '',
    },
    course: { id: 5, title: 'Standard 8', course_type: 'free' },
    subject_display: 'Urdu, Islamiyat',
    teaching_mode: 'in_person',
    budget_amount: '7000-8000',
    budget_type: 'per_month',
    duration_value: 5,
    duration_unit: 'month',
    location: 'Multan',
    status: 'open',
    applications_count: 8,
    created_at: '2025-10-20',
    updated_at: '2025-10-23',
    time_ago: '5 Days Ago',
    deadline: '2025-11-12',
    can_apply: true,
    additional_notes:
      'Female tutor preferred. Should focus on improving reading and writing skills.',
    selected_teacher: null,
  },
  {
    id: 6,
    title: 'IGCSE Economics & Business Studies Tutor',
    description:
      'Expert tutor needed for IGCSE Economics and Business Studies. Must be familiar with latest syllabus and have proven track record of student success in these subjects.',
    student: {
      id: 6,
      username: 'student6',
      full_name: 'Hassan Raza',
      profile_picture: '',
    },
    course: { id: 6, title: 'IGCSE', course_type: 'paid' },
    subject_display: 'Economics, Business Studies',
    teaching_mode: 'online',
    budget_amount: '18000',
    budget_type: 'per_month',
    duration_value: 5,
    duration_unit: 'month',
    location: 'Remote',
    status: 'open',
    applications_count: 9,
    created_at: '2025-10-17',
    updated_at: '2025-10-24',
    time_ago: '8 Days Ago',
    deadline: '2025-11-08',
    can_apply: true,
    additional_notes:
      'Should provide past papers and marking schemes. Regular assessments required.',
    selected_teacher: null,
  },
  {
    id: 7,
    title: 'Chemistry Tutor for FSc Pre-Medical',
    description:
      'Highly qualified Chemistry tutor required for FSc Pre-Medical student. Must have deep understanding of organic, inorganic and physical chemistry with medical entrance exam preparation experience.',
    student: {
      id: 7,
      username: 'student7',
      full_name: 'Aisha Tariq',
      profile_picture: '',
    },
    course: { id: 7, title: 'FSc Pre-Medical', course_type: 'paid' },
    subject_display: 'Chemistry',
    teaching_mode: 'in_person',
    budget_amount: '14000',
    budget_type: 'per_month',
    duration_value: 8,
    duration_unit: 'month',
    location: 'Lahore',
    status: 'open',
    applications_count: 18,
    created_at: '2025-10-16',
    updated_at: '2025-10-23',
    time_ago: '9 Days Ago',
    deadline: '2025-11-03',
    can_apply: true,
    additional_notes:
      'MDCAT preparation also required. Must provide comprehensive notes and practice questions.',
    selected_teacher: null,
  },
  {
    id: 8,
    title: 'Mathematics & Statistics for BS Student',
    description:
      'University level Mathematics and Statistics tutor needed for BS student. Topics include calculus, linear algebra, probability and statistical analysis. Research methodology guidance also appreciated.',
    student: {
      id: 8,
      username: 'student8',
      full_name: 'Bilal Ahmed',
      profile_picture: '',
    },
    course: { id: 8, title: 'BS Mathematics', course_type: 'paid' },
    subject_display: 'Mathematics, Statistics',
    teaching_mode: 'online',
    budget_amount: '20000',
    budget_type: 'per_month',
    duration_value: 4,
    duration_unit: 'month',
    location: 'Remote',
    status: 'open',
    applications_count: 6,
    created_at: '2025-10-22',
    updated_at: '2025-10-24',
    time_ago: '3 Days Ago',
    deadline: '2025-11-18',
    can_apply: true,
    additional_notes:
      'Must be available for evening sessions. Graduate level teaching experience preferred.',
    selected_teacher: null,
  },
  {
    id: 9,
    title: 'English Language & Literature - Standard 11',
    description:
      'Experienced English teacher required for Standard 11 student. Focus on improving vocabulary, grammar, essay writing, and literature analysis. Preparation for board exams required.',
    student: {
      id: 9,
      username: 'student9',
      full_name: 'Maryam Noor',
      profile_picture: '',
    },
    course: { id: 9, title: 'Standard 11', course_type: 'free' },
    subject_display: 'English Language, English Literature',
    teaching_mode: 'in_person',
    budget_amount: '9000',
    budget_type: 'per_month',
    duration_value: 6,
    duration_unit: 'month',
    location: 'Faisalabad',
    status: 'open',
    applications_count: 11,
    created_at: '2025-10-14',
    updated_at: '2025-10-22',
    time_ago: '11 Days Ago',
    deadline: '2025-10-31',
    can_apply: true,
    additional_notes:
      'Student needs to improve speaking and writing skills. Regular homework assignments required.',
    selected_teacher: null,
  },
  {
    id: 10,
    title: 'Physics & Mathematics for O-Level',
    description:
      'Dual subject tutor needed for O-Level Physics and Mathematics. Should be able to explain concepts with practical examples and conduct regular tests to track progress.',
    student: {
      id: 10,
      username: 'student10',
      full_name: 'Usman Khalid',
      profile_picture: '',
    },
    course: { id: 10, title: 'O-Level', course_type: 'paid' },
    subject_display: 'Physics, Mathematics',
    teaching_mode: 'online',
    budget_amount: '16000',
    budget_type: 'per_month',
    duration_value: 5,
    duration_unit: 'month',
    location: 'Remote',
    status: 'open',
    applications_count: 14,
    created_at: '2025-10-13',
    updated_at: '2025-10-21',
    time_ago: '12 Days Ago',
    deadline: '2025-11-02',
    can_apply: true,
    additional_notes:
      'Must provide digital whiteboard sessions. Previous O-Level teaching experience mandatory.',
    selected_teacher: null,
  },
  {
    id: 11,
    title: 'Quran & Arabic Language Teacher',
    description:
      'Seeking a qualified Qari/Qaria to teach Quran with Tajweed and basic Arabic language. Must have Ijazah and experience in teaching children. Patient and kind approach required.',
    student: {
      id: 11,
      username: 'student11',
      full_name: 'Hamza Yousaf',
      profile_picture: '',
    },
    course: { id: 11, title: 'Islamic Studies', course_type: 'free' },
    subject_display: 'Quran, Arabic Language',
    teaching_mode: 'in_person',
    budget_amount: '6000',
    budget_type: 'per_month',
    duration_value: 12,
    duration_unit: 'month',
    location: 'Rawalpindi',
    status: 'open',
    applications_count: 20,
    created_at: '2025-10-12',
    updated_at: '2025-10-20',
    time_ago: '13 Days Ago',
    deadline: '2025-11-06',
    can_apply: true,
    additional_notes:
      'Morning sessions preferred. Must teach proper pronunciation and Tajweed rules.',
    selected_teacher: null,
  },
  {
    id: 12,
    title: 'Web Development & Programming Bootcamp',
    description:
      'Looking for a professional web developer to teach HTML, CSS, JavaScript, and React. Student wants to build real-world projects and prepare for freelancing career. Intensive training required.',
    student: {
      id: 12,
      username: 'student12',
      full_name: 'Sana Arif',
      profile_picture: '',
    },
    course: { id: 12, title: 'Web Development', course_type: 'paid' },
    subject_display: 'HTML, CSS, JavaScript, React',
    teaching_mode: 'online',
    budget_amount: '25000',
    budget_type: 'per_month',
    duration_value: 6,
    duration_unit: 'month',
    location: 'Remote',
    status: 'open',
    applications_count: 22,
    created_at: '2025-10-11',
    updated_at: '2025-10-24',
    time_ago: '14 Days Ago',
    deadline: '2025-11-20',
    can_apply: true,
    additional_notes:
      'Project-based learning required. Must teach industry best practices and modern development tools.',
    selected_teacher: null,
  },
];
